# Generated by Django 5.0 on 2024-02-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isimm', '0013_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='student_images/'),
        ),
    ]
