# Generated by Django 5.0 on 2024-02-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isimm', '0014_student_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='birthdate',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(default='N/A', max_length=255),
        ),
    ]
