# Generated by Django 5.0 on 2024-02-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isimm', '0015_student_birthdate_student_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='N/A', max_length=255),
        ),
    ]
