# Generated by Django 5.0 on 2024-02-27 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isimm', '0016_rename_name_student_first_name_student_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(default='N/A', max_length=255),
        ),
    ]
